// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures
struct Monster
{
  struct Monster_vtable *vptr;
};
struct Foo
{
  struct Foo_vtable *vptr;
};
// vtables structures
struct Monster_vtable
{
};

struct Foo_vtable
{
  int (*foo)();
};


// methods
int Foo_foo(struct Foo * this)
{
  int sum;

  sum = 0;  sum = sum + 1;  sum = sum + 1;  sum = sum + 1;  sum = sum + 1;  sum = sum + 1;  sum = sum + 1;  sum = sum + 1;  sum = sum + 1;  sum = sum + 1;  sum = sum + 1;  return sum;
}

// vtables
struct Monster_vtable Monster_vtable_ = 
{
};

struct Foo_vtable Foo_vtable_ = 
{
  Foo_foo,
};


// main method
int Tiger_main ()
{
  struct Foo * null;
  System_out_println ((null=((struct Foo*)(Tiger_new (&Foo_vtable_, sizeof(struct Foo)))), null->vptr->foo(null)));
}




