// This is automatically generated by the Tiger compiler.
// Do NOT modify!

//declaration
struct Sum_vtable Sum_vtable_;
struct Doit_vtable Doit_vtable_;
// structures
struct Sum
{
  struct Sum_vtable *vptr;
};
struct Doit
{
  struct Doit_vtable *vptr;
};
// vtables structures
struct Sum_vtable
{
};

struct Doit_vtable
{
  int (*doit)();
};


// methods
int Doit_doit(struct Doit * this, unsigned char n)
{
  int sum;
  int i;

  i = 0;
  sum = 0;
  while(  i < 1)
        sum = sum + i;
      return sum;
}

// vtables
struct Sum_vtable Sum_vtable_ = 
{
};

struct Doit_vtable Doit_vtable_ = 
{
  Doit_doit,
};


// main method
int Tiger_main ()
{
  struct null * doit;
  System_out_println ((doit=((struct Doit*)(Tiger_new (&Doit_vtable_, sizeof(struct Doit)))), doit->vptr->doit(doit, 101)));
}




