; This is automatically generated by the Tiger compiler.
; Do NOT modify!

.class public Foo
.super java/lang/Object

.method public <init>()V
    aload 0
    invokespecial java/lang/Object/<init>()V
    return
.end method


.method public foo()I
.limit stack 4096
.limit locals 3
    ldc 0
    istore 1
    istore 1
    istore 1
    istore 1
    istore 1
    istore 1
    istore 1
    istore 1
    istore 1
    istore 1
    istore 1
    iload 1
    ireturn
.end method
