// This is automatically generated by the Tiger compiler.
// Do NOT modify!

//declaration
struct LinkedList_vtable LinkedList_vtable_;
struct Element_vtable Element_vtable_;
struct List_vtable List_vtable_;
struct LL_vtable LL_vtable_;
// structures
struct LinkedList
{
  struct LinkedList_vtable *vptr;
};
struct Element
{
  struct Element_vtable *vptr;
  int Age;
  int Salary;
  unsigned char Married;
};
struct List
{
  struct List_vtable *vptr;
  struct Element * elem;
  struct List * next;
  unsigned char end;
};
struct LL
{
  struct LL_vtable *vptr;
};
// vtables structures
struct LinkedList_vtable
{
};

struct Element_vtable
{
  unsigned char (*Init)();
  int (*GetAge)();
  int (*GetSalary)();
  unsigned char (*GetMarried)();
  unsigned char (*Equal)();
  unsigned char (*Compare)();
};

struct List_vtable
{
  unsigned char (*Init)();
  unsigned char (*InitNew)();
  struct List * (*Insert)();
  unsigned char (*SetNext)();
  struct List * (*Delete)();
  int (*Search)();
  unsigned char (*GetEnd)();
  struct Element * (*GetElem)();
  struct List * (*GetNext)();
  unsigned char (*Print)();
};

struct LL_vtable
{
  int (*Start)();
};


// methods
unsigned char Element_Init(struct Element * this, int v_Age, int v_Salary, unsigned char v_Married)
{

  this->Age = v_Age;
  this->Salary = v_Salary;
  this->Married = v_Married;
  return 1;
}
int Element_GetAge(struct Element * this)
{

  return this->Age;
}
int Element_GetSalary(struct Element * this)
{

  return this->Salary;
}
unsigned char Element_GetMarried(struct Element * this)
{

  return this->Married;
}
unsigned char Element_Equal(struct Element * this, struct Element * other)
{
  unsigned char ret_val;
  int aux01;
  int aux02;
  int nt;
  struct Element * GetAge;
  struct Element * Compare;
  struct Element * GetSalary;
  struct Element * GetMarried;

  ret_val = 1;
  aux01 = (GetAge=other, GetAge->vptr->GetAge(GetAge));
  if (!(Compare=this, Compare->vptr->Compare(Compare, aux01, this->Age)))
    ret_val = 0;
  else
{
        aux02 = (GetSalary=other, GetSalary->vptr->GetSalary(GetSalary));
        if (!(Compare=this, Compare->vptr->Compare(Compare, aux02, this->Salary)))
      ret_val = 0;
    else
      if (this->Married)
        if (!(GetMarried=other, GetMarried->vptr->GetMarried(GetMarried)))
          ret_val = 0;
        else
          nt = 0;

      else
        if ((GetMarried=other, GetMarried->vptr->GetMarried(GetMarried)))
          ret_val = 0;
        else
          nt = 0;



    }

  return ret_val;
}
unsigned char Element_Compare(struct Element * this, int num1, int num2)
{
  unsigned char retval;
  int aux02;

  retval = 0;
  aux02 = num2 + 1;
  if (num1 < num2)
    retval = 0;
  else
    if (!num1 < aux02)
      retval = 0;
    else
      retval = 1;


  return retval;
}
unsigned char List_Init(struct List * this)
{

  this->end = 1;
  return 1;
}
unsigned char List_InitNew(struct List * this, struct Element * v_elem, struct List * v_next, unsigned char v_end)
{

  this->end = v_end;
  this->elem = v_elem;
  this->next = v_next;
  return 1;
}
struct List * List_Insert(struct List * this, struct Element * new_elem)
{
  unsigned char ret_val;
  struct List * aux03;
  struct List * aux02;
  struct List * InitNew;

  aux03 = this;
  aux02 = ((struct List*)(Tiger_new (&List_vtable_, sizeof(struct List))));
  ret_val = (InitNew=aux02, InitNew->vptr->InitNew(InitNew, new_elem, aux03, 0));
  return aux02;
}
unsigned char List_SetNext(struct List * this, struct List * v_next)
{

  this->next = v_next;
  return 1;
}
struct List * List_Delete(struct List * this, struct Element * e)
{
  struct List * my_head;
  unsigned char ret_val;
  unsigned char aux05;
  struct List * aux01;
  struct List * prev;
  unsigned char var_end;
  struct Element * var_elem;
  int aux04;
  int nt;
  struct Element * Equal;
  struct List * GetNext;
  struct List * SetNext;
  struct List * GetEnd;
  struct List * GetElem;

  my_head = this;
  ret_val = 0;
  aux04 = 0 - 1;
  aux01 = this;
  prev = this;
  var_end = this->end;
  var_elem = this->elem;
  while(  !var_end && !ret_val)
    {
        if ((Equal=e, Equal->vptr->Equal(Equal, var_elem)))
{
            ret_val = 1;
            if (aux04 < 0)
{
                my_head = (GetNext=aux01, GetNext->vptr->GetNext(GetNext));
        }
      else
{
                System_out_println (0 - 555);
                aux05 = (SetNext=prev, SetNext->vptr->SetNext(SetNext, (GetNext=aux01, GetNext->vptr->GetNext(GetNext))));
                System_out_println (0 - 555);
        }

      }
    else
      nt = 0;

        if (!ret_val)
{
            prev = aux01;
            aux01 = (GetNext=aux01, GetNext->vptr->GetNext(GetNext));
            var_end = (GetEnd=aux01, GetEnd->vptr->GetEnd(GetEnd));
            var_elem = (GetElem=aux01, GetElem->vptr->GetElem(GetElem));
            aux04 = 1;
      }
    else
      nt = 0;

    }
      return my_head;
}
int List_Search(struct List * this, struct Element * e)
{
  int int_ret_val;
  struct List * aux01;
  struct Element * var_elem;
  unsigned char var_end;
  int nt;
  struct Element * Equal;
  struct List * GetNext;
  struct List * GetEnd;
  struct List * GetElem;

  int_ret_val = 0;
  aux01 = this;
  var_end = this->end;
  var_elem = this->elem;
  while(  !var_end)
    {
        if ((Equal=e, Equal->vptr->Equal(Equal, var_elem)))
{
            int_ret_val = 1;
      }
    else
      nt = 0;

        aux01 = (GetNext=aux01, GetNext->vptr->GetNext(GetNext));
        var_end = (GetEnd=aux01, GetEnd->vptr->GetEnd(GetEnd));
        var_elem = (GetElem=aux01, GetElem->vptr->GetElem(GetElem));
    }
      return int_ret_val;
}
unsigned char List_GetEnd(struct List * this)
{

  return this->end;
}
struct Element * List_GetElem(struct List * this)
{

  return this->elem;
}
struct List * List_GetNext(struct List * this)
{

  return this->next;
}
unsigned char List_Print(struct List * this)
{
  struct List * aux01;
  unsigned char var_end;
  struct Element * var_elem;
  struct Element * GetAge;
  struct List * GetNext;
  struct List * GetEnd;
  struct List * GetElem;

  aux01 = this;
  var_end = this->end;
  var_elem = this->elem;
  while(  !var_end)
    {
        System_out_println ((GetAge=var_elem, GetAge->vptr->GetAge(GetAge)));
        aux01 = (GetNext=aux01, GetNext->vptr->GetNext(GetNext));
        var_end = (GetEnd=aux01, GetEnd->vptr->GetEnd(GetEnd));
        var_elem = (GetElem=aux01, GetElem->vptr->GetElem(GetElem));
    }
      return 1;
}
int LL_Start(struct LL * this)
{
  struct List * head;
  struct List * last_elem;
  unsigned char aux01;
  struct Element * el01;
  struct Element * el02;
  struct Element * el03;
  struct List * Init;
  struct List * Print;
  struct List * Insert;
  struct List * Search;
  struct List * Delete;

  last_elem = ((struct List*)(Tiger_new (&List_vtable_, sizeof(struct List))));
  aux01 = (Init=last_elem, Init->vptr->Init(Init));
  head = last_elem;
  aux01 = (Init=head, Init->vptr->Init(Init));
  aux01 = (Print=head, Print->vptr->Print(Print));
  el01 = ((struct Element*)(Tiger_new (&Element_vtable_, sizeof(struct Element))));
  aux01 = (Init=el01, Init->vptr->Init(Init, 25, 37000, 0));
  head = (Insert=head, Insert->vptr->Insert(Insert, el01));
  aux01 = (Print=head, Print->vptr->Print(Print));
  System_out_println (10000000);
  el01 = ((struct Element*)(Tiger_new (&Element_vtable_, sizeof(struct Element))));
  aux01 = (Init=el01, Init->vptr->Init(Init, 39, 42000, 1));
  el02 = el01;
  head = (Insert=head, Insert->vptr->Insert(Insert, el01));
  aux01 = (Print=head, Print->vptr->Print(Print));
  System_out_println (10000000);
  el01 = ((struct Element*)(Tiger_new (&Element_vtable_, sizeof(struct Element))));
  aux01 = (Init=el01, Init->vptr->Init(Init, 22, 34000, 0));
  head = (Insert=head, Insert->vptr->Insert(Insert, el01));
  aux01 = (Print=head, Print->vptr->Print(Print));
  el03 = ((struct Element*)(Tiger_new (&Element_vtable_, sizeof(struct Element))));
  aux01 = (Init=el03, Init->vptr->Init(Init, 27, 34000, 0));
  System_out_println ((Search=head, Search->vptr->Search(Search, el02)));
  System_out_println ((Search=head, Search->vptr->Search(Search, el03)));
  System_out_println (10000000);
  el01 = ((struct Element*)(Tiger_new (&Element_vtable_, sizeof(struct Element))));
  aux01 = (Init=el01, Init->vptr->Init(Init, 28, 35000, 0));
  head = (Insert=head, Insert->vptr->Insert(Insert, el01));
  aux01 = (Print=head, Print->vptr->Print(Print));
  System_out_println (2220000);
  head = (Delete=head, Delete->vptr->Delete(Delete, el02));
  aux01 = (Print=head, Print->vptr->Print(Print));
  System_out_println (33300000);
  head = (Delete=head, Delete->vptr->Delete(Delete, el01));
  aux01 = (Print=head, Print->vptr->Print(Print));
  System_out_println (44440000);
  return 0;
}

// vtables
struct LinkedList_vtable LinkedList_vtable_ = 
{
};

struct Element_vtable Element_vtable_ = 
{
  Element_Init,
  Element_GetAge,
  Element_GetSalary,
  Element_GetMarried,
  Element_Equal,
  Element_Compare,
};

struct List_vtable List_vtable_ = 
{
  List_Init,
  List_InitNew,
  List_Insert,
  List_SetNext,
  List_Delete,
  List_Search,
  List_GetEnd,
  List_GetElem,
  List_GetNext,
  List_Print,
};

struct LL_vtable LL_vtable_ = 
{
  LL_Start,
};


// main method
int Tiger_main ()
{
  struct LL * Start;
  System_out_println ((Start=((struct LL*)(Tiger_new (&LL_vtable_, sizeof(struct LL)))), Start->vptr->Start(Start)));
}




