// This is automatically generated by the Tiger compiler.
// Do NOT modify!

//declaration
struct QuickSort_vtable QuickSort_vtable_;
struct QS_vtable QS_vtable_;
// structures
struct QuickSort
{
  struct QuickSort_vtable *vptr;
};
struct QS
{
  struct QS_vtable *vptr;
  int * number;
  int size;
};
// vtables structures
struct QuickSort_vtable
{
};

struct QS_vtable
{
  int (*Start)();
  int (*Sort)();
  int (*Print)();
  int (*Init)();
};


// methods
int QS_Start(struct QS * this, int sz)
{
  int aux01;
  struct QS * Init;
  struct QS * Print;
  struct QS * Sort;

  aux01 = (Init=this, Init->vptr->Init(Init, sz));
  aux01 = (Print=this, Print->vptr->Print(Print));
  System_out_println (9999);
  aux01 = this->size - 1;
  aux01 = (Sort=this, Sort->vptr->Sort(Sort, 0, aux01));
  aux01 = (Print=this, Print->vptr->Print(Print));
  return 0;
}
int QS_Sort(struct QS * this, int left, int right)
{
  int v;
  int i;
  int j;
  int nt;
  int t;
  unsigned char cont01;
  unsigned char cont02;
  int aux03;
  struct QS * Sort;

  t = 0;
  if (left < right)
{
        v = this->number[right];
        i = left - 1;
        j = right;
        cont01 = 1;
        while(    cont01)
      {
            cont02 = 1;
            while(      cont02)
        {
                i = i + 1;
                aux03 = this->number[i];
                if (!aux03 < v)
          cont02 = 0;
        else
          cont02 = 1;

        }
                cont02 = 1;
                while(        cont02)
          {
                    j = j - 1;
                    aux03 = this->number[j];
                    if (!v < aux03)
            cont02 = 0;
          else
            cont02 = 1;

          }
                    t = this->number[i];
                    this->number[i] = this->number[j];
                    this->number[j] = t;
                    if (j < i + 1)
            cont01 = 0;
          else
            cont01 = 1;

                        }
            this->number[j] = this->number[i];
            this->number[i] = this->number[right];
            this->number[right] = t;
            nt = (Sort=this, Sort->vptr->Sort(Sort, left, i - 1));
            nt = (Sort=this, Sort->vptr->Sort(Sort, i + 1, right));
          }
  else
    nt = 0;

  return 0;
}
int QS_Print(struct QS * this)
{
  int j;

  j = 0;
  while(  j < this->size)
    {
        System_out_println (this->number[j]);
        j = j + 1;
    }
      return 0;
}
int QS_Init(struct QS * this, int sz)
{

  this->size = sz;
  this->number = (int *)malloc(sizeof(int)*sz);
  this->number[0] = 20;
  this->number[1] = 7;
  this->number[2] = 12;
  this->number[3] = 18;
  this->number[4] = 2;
  this->number[5] = 11;
  this->number[6] = 6;
  this->number[7] = 9;
  this->number[8] = 19;
  this->number[9] = 5;
  return 0;
}

// vtables
struct QuickSort_vtable QuickSort_vtable_ = 
{
};

struct QS_vtable QS_vtable_ = 
{
  QS_Start,
  QS_Sort,
  QS_Print,
  QS_Init,
};


// main method
int Tiger_main ()
{
  struct QS * Start;
  System_out_println ((Start=((struct QS*)(Tiger_new (&QS_vtable_, sizeof(struct QS)))), Start->vptr->Start(Start, 10)));
}




